- hotdoc/core/links.py
They are always recreated anyway and pickling them might take a big
long time on system having many gtk doc books.
> links: Do not pickle external links

- hotdoc/core/doc_repo.py
- hotdoc/core/file_includer.py
We should make sure that any inclusion that is not markdown formatted is
put inside a code block. And inside code blocks, we should never let
inclusions happen (as it is a protected block, that part is yet to be
fixed in another commit)
First phase of fixing #48
> Handle comment blocks when including files

- setup.py
I ran into this while making a Debian package. An absolute path here does
not work, since it will recreate the entire path hierarchy in the build
dir.
> setup.py: Use relative path for package data

- setup.py
It was being included as package_data for 'hotdoc', so the path had to be
relative to 'hotdoc' as well.
A straggler from my previous pull request. It fixed the build, but hotdoc_bootstrap_theme wasn't being included in the binary. Oops!
> setup: Fix hotdoc_bootstrap_theme path

- hotdoc/utils/hotdoc.m4
This was using some previous output of --has-extension and didn't work
anymore, reporting all extensions as found. Change it to use the exit
code instead.
> utils: Fix extension checking in HOTDOC_CHECK

- hotdoc/extensions/git_upload/git_upload_extension.py
Allows a subpath of a remote repo URL, such as `--git-upload-repository=https://github.com/hotdoc/hotdoc/docs/mydir`.
> Git upload remote repo path

- hotdoc/hotdoc
It seems to be a limitation of setuptools, that your startup script
cannot be in an encoding other than that of the environment. So if you
install Hotdoc with `pip install -e` or `setup.py develop` then try to
run it with LANG=C, you'll get a UnicodeDecodeError.
Removing the copyright signs from the startup script makes it work again.
> build: Make startup script ASCII-only

- hotdoc/core/project.py
Prism does recognize 'js' as a valid language, but only if
prism-javascript.min.js is loaded first. If there are no code blocks
with `class="language-javascript"`, then an included .js file won't
get highlighted. This should fix that.
> Add .js to include lang mapping

- hotdoc/extensions/gst/gst_extension.py
This was never possible, the symbol unique name is GTypeName->template_name
> gst: Render PadTemplate documentation

- hotdoc/core/project.py
It was not really useful as we won't be able to build the documentation
of a same lib for two of its versions at the same time because of
symbole name uniqueness
> Remove version in output names and make it informatory only

- setup.py
hotdoc/hotdoc_bootstrap_theme/Makefile uses non-standard syntaxes which
are specific to GNU make. On platforms which uses BSD make as the
default make command, it causes the installation to fail because
Makefile cannot be parsed. 'gmake' is a common name for GNU make on
systems which don't use GNU make as the default make command, so
searching for 'gmake' first is much likely to find the correct make.
This fixes installation failure on FreeBSD:
```
make
make: "/home/lantw44/gnome/source/hotdoc/hotdoc/hotdoc_bootstrap_theme/Makefile" line 20: Need an operator
make: "/home/lantw44/gnome/source/hotdoc/hotdoc/hotdoc_bootstrap_theme/Makefile" line 27: Need an operator
make: "/home/lantw44/gnome/source/hotdoc/hotdoc/hotdoc_bootstrap_theme/Makefile" line 51: Need an operator
make: …
```
> setup: search for 'gmake' in addition to 'make'

- hotdoc/core/formatter.py
- hotdoc/extensions/gst/gst_extension.py
And properly use GIClassSymbol for other classed types as they actually
are GObject and we need the surounding logic there.
> gst: Move other class types to their own pages

- hotdoc/extensions/gst/gst_extension.py
> gst: Use plugin name to reference plugins

- hotdoc/utils/utils.py
- setup.py
The current pin is for a version from 2013, and it hasn't broken in 7 years of backwards-compatible releases. Out of a bunch of dependencies in this project, this should not be a high priority to pin!
> remove unneeded pin on python-pkgconfig version

- hotdoc/parsers/gtk_doc.py
- hotdoc/utils/utils.py
- setup.py
It's trivially implemented in a couple lines of os.getenv, and the xdg module clashes with the *other* xdg module.
https://pypi.org/project/xdg/
https://pypi.org/project/pyxdg/
The former is a relatively recent package that ONLY provides the XDG base directory specification, but calls itself "xdg".
The latter is Freedesktop's own module that has been around for a lot longer, and provides the base directory variables in the submodule xdg.BaseDirectory.*, in addition to providing code relevant to several other xdg standards.
The existence of the former is confusing and redundant, and the use of either one is a bit overkill; the spec is not complicated, let's just provide it ourselves.
> drop dependency on xdg

- hotdoc/core/symbols.py
- hotdoc/extensions/gi/symbols.py
This way we set comments on them and they are properly taken into account to check Since markers.
> gi: Add class structure fields as children of the GIClassSymbol

- .github/workflows/python.yml
Using python setup.py develop directly is a very hairy approach... it means all dependencies are getting resolved via easy_install and the resulting breakage is atrocious (installing prereleases of dependencies, not respecting python_requires).
easy_install is totally deprecated and should never be used... pip install --editable wraps setuptools develop mode while using the pip dependency resolver which is actually maintained and therefore works.
> CI: use pip for editable installs

- hotdoc/core/extension.py
- hotdoc/core/inclusions.py
- hotdoc/core/tests/test_inclusions.py
- hotdoc/core/tree.py
- hotdoc/parsers/search_module.c
This PR fixes a segfault in `search_module.c` and improves the logic for handling relative paths for the generated HTML files.
> Fix segfault in search_module.c

- hotdoc/extensions/syntax_highlighting/syntax_extension.py
- setup.py
The use case for this is supporting HTML (primarily hyperlinks) in custom code blocks. For instance, the following code will insert a hyperlink in the resulting code block:
```
Normal markdown here.
Use inline HTML to generate a code block:
<pre><code class="language-meson">
<a href="RefMan_elementary_str.html">str</a> str.replace(arg1, arg2)
</code></pre>
```
> Add option for enabling prism-keep-markup

- documentation/markdown_files/the-markdown-pages.markdown
As mentioned in #232, I stumbled across these when looking through the source code. This is not a good user experience and I strongly recommend investing in some sort of reference manual where all features are documented.
I did not add any description for the keys where I was not sure what they do (or what they are supposed to do).
> Add some documentation for the metadata keys

- hotdoc/core/symbols.py
This fixes a problem in resolving alias links.  That latter is illustrated by the online GStreamer plugins documentation, e.g. https://gstreamer.freedesktop.org/documentation/audiorate/index.html?gi-language=c.  There are quite some property references in the description, and they end up with empty title and a dangling `href`.
See the commit message for additional details. Of course, there may be other ways to address this, such as explicitly also resolving the alias links (e.g. in `Page.__resolve_symbols), etc.
> symbols: do not list aliases as children

- hotdoc/hotdoc_dep_printer.py
Commit 212d202 changed the name of the configuration class in `hotdoc.core.config` from `ConfigParser` to just `Config`.
`hotdoc_dep_printer.py` was still using the old name, making it unusable.
(And even un-importable, so no `pydoc` access:)
```console
$ pydoc3 hotdoc.hotdoc_dep_printer
problem in hotdoc.hotdoc_dep_printer - ImportError:
cannot import name 'ConfigParser' from 'hotdoc.core.config'
(.../site-packages/hotdoc/core/config.py)
> hotdoc_dep_printer: fix Config class name

- .github/workflows/python.yml
And add 3.11 instead, CI was failing github side for 3.6 with:
> Error: Version 3.6 with arch x64 not found
> workflows: remove CI for 3.6

- hotdoc/extensions/gst/gst_extension.py
- hotdoc/tests/test_hotdoc.py
When symbol.formatted_doc exists, it is already rendered by the base template. When it is not, add the plugin display name as the title.
> gst_extension: don't duplicate plugin documentation

- hotdoc/extensions/dbus/dbus_extension.py
dbus_extension.py on multiple places will call add_comment with None as the argument if no comment is present. The add_comment function does not handle None as an argument, so this change checks for None before calling.
Example of a traceback I got before this fix:
```
An unknown error happened while building the documentation and hotdoc cannot recover from it. Please report a bug with this error message and the steps to reproduce it
Traceback (most recent call last):
File "/home/johanbj/.local/lib/python3.9/site-packages/hotdoc/run_hotdoc.py", line 294, in execute_command
app.run()
File "/home/johanbj/.local/lib/python3.9/site-packages/hotdoc/run_hotdoc.py", line 107, in run
self.project.setup()
File "/home/johanbj/.local/lib/python3.9/site-packages/hotdoc/core/project.py", line 183, in …
```
> extensions/dbus: Don't crash when comment is missing

- requirements.txt
- setup.py
PyYaml 5.4.1 can no longer be installed via `pip`, because its `setup.cfg` is too outdated.
```console
$ python3 -m venv venv
$ ./venv/bin/activate
$ pip install pyyaml==5.4.1
Collecting pyyaml==5.4.1
Using cached PyYAML-5.4.1.tar.gz (175 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [68 lines of output]
/tmp/pip-build-env-ol926mnw/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
!!
********************************************************************************
The license_file parameter is deprecated, use license_files instead.
By 2023-Oct-30, you need …
```
> Bump pyyaml dependency to ">=6" (6.0.1)

- hotdoc/extensions/c/c_extension.py
Clang version N.M.O now installs files to `{libdir}/clang/N/` instead of `{libdir}/clang/N.M.O/`. Check both possibilities when scanning for headers.
(The ordering on the `itertools.product` will first check the full version under `lib`, then `lib64`, and then do the same for the major-version number.)
> c_extension: Fix clang header detection

- hotdoc/extensions/gi/annotation_parser.py
A comment above `OPTIONAL_HELP` mentioned "the previous one", which made sense until commit 93eea55 inserted a message between them.
To protect against future ordering changes, reference the other message by name instead of proximity.
> annotation_parser: Fix comment reference

- hotdoc/extensions/check_since_markers/check_since_markers.py
No need to require a Since tag for a symbol that is not documented anywhere.
> check_since_markers: don't warn for private symbols

- .github/workflows/label-conflicts.yml
A completely take-it-or-leave-it suggestion, something I've used in other projects. This PR adds an Actions workflow (using [eps1lon/actions-label-merge-conflict](https://github.com/eps1lon/actions-label-merge-conflict)) that implements a missing GitHub feature: The ability to see, at a glance from the PR list, which PRs are mergeable and which aren't.
Before merging this, a label for PRs with conflicts should be created at https://github.com/hotdoc/hotdoc/labels. Its name should match the `dirtyLabel` option passed to the action. I've initially set that to `"conflicts"`, but it can be anything.
There are also two automated PR comment texts in the config, I'd appreciate a review of their content as well. (It's also possible to delete either or both of those messages, and have the action …
> Add a workflow to label PRs with merge conflicts

- setup.py
I missed that there was `pre-commit` integration in `setup.py` that should no longer be there (as it no longer works after #266).
At some point we can look at replacing this with a command runner than installs `pre-commit`, then runs `pre-commit install --install-hooks`, the moral equivalent. But for right now, with the old `pre-commit` script removed from the repo, the only function this has is to break attempted development builds/installs.
> Remove LinkPreCommitHook from setup.py

- hotdoc/extensions/c/utils.py
- hotdoc/extensions/gi/transition_scripts/hotdoc_gtk_doc_porter
The line-by-line detection defintely broke with emojis in UTF-8 encoded files, and it doesn't make sense anyway.
For simplicity, let's stop doing character set detection at all, and expect input to be UTF-8.
> extensions: Stop doing line-by-line character set detection

- hotdoc/extensions/gi/utils.py
- hotdoc/utils/utils.py
- setup.py
This PR eliminates use of setuptools' [deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html#package-discovery-and-resource-access-using-pkg-resources) `pkg_resources` in `hotdoc.utils.utils` and `hotdoc.extensions.gi.utils`, substituting equivalent APIs provided by `importlib.metadata.entry_points()`.
The `entry_points()` function used is actually imported from `backports.entry_points_selectable` (a new dependency, added to `setup.py`), which ensures that calls to `entry_points()` can take filtering arguments even in Python < 3.10, where `importlib.metadata` didn't natively support such usage.
(In practice, for recent Python 3.10+ releases, `backports.entry_points_selectable.entry_points` will be `importlib.metadata.entry_points`.)
The resulting `hotdoc` package passes all …
> Eliminate dependency on deprecated setuptools.pkg_resources

- hotdoc/extensions/gi/gi_extension.py
Since gobject-introspection 1.80 other fields are added (like documentation) and therefore the callback child might actualy be the 2nd child.
> gi: Don't assume position of callback child within fields

- documentation/markdown_files/installing.markdown
Refering to what discussed in https://github.com/hotdoc/hotdoc/issues/286
> Update installing documentation to include clang

- hotdoc/extensions/c/c_extension.py
When using brew it is the way to specify where to find llvm-config in meson and other tools, we should also support it.
> c-extension: Use the LLVM_CONFIG env variable if present

- hotdoc/extensions/c/utils.py
- requirements.txt
- setup.py
Not used since:
2f3bb61 ("extensions: Stop doing line-by-line character set detection", 2023-10-13)
> Remove unused cchardet import and dependency

- .github/workflows/python.yml
Otherwise Python 3.10 is considered as 3.1 by GitHub Actions…
> CI: Python version are strings

- hotdoc/extensions/gi/transition_scripts/hotdoc_gtk_doc_porter
Allows to use Python 3.13
Closes: https://github.com/hotdoc/hotdoc/issues/288
> gi: Use html.escape instead of cgi.escape
